---
# START Service
apiVersion: v1
kind: Service
metadata:
  name: tickets
  labels:
    app: tickets
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    name: tickets
# END SERVICE
